# Generated by Django 5.0 on 2023-12-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djrestfm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
