# Generated by Django 5.0 on 2023-12-31 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djrestfm', '0002_delete_student_subjects_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=100)),
                ('marks', models.FloatField(default=0)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djrestfm.subjects')),
            ],
        ),
    ]
