# Generated by Django 5.0 on 2023-12-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djrestfm', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sub',
            new_name='subject',
        ),
    ]
