# Generated by Django 5.0 on 2024-02-29 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='username',
        ),
        migrations.AddField(
            model_name='cuser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuser',
            name='Email',
            field=models.EmailField(default='null', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='Phone',
            field=models.CharField(default='null', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='user_profile',
            field=models.ImageField(default='null', upload_to='profile'),
        ),
    ]
