# Generated by Django 5.0 on 2024-03-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_cuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cuser',
        ),
    ]
