# Generated by Django 5.0 on 2024-03-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_user',
            fields=[
                ('username', models.TextField(default=None, max_length=50, unique=True)),
                ('Email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('E_varify', models.BooleanField(default=False)),
            ],
        ),
    ]
