# Generated by Django 5.0 on 2024-03-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='Key',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
