# Generated by Django 5.0 on 2024-03-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
