# Generated by Django 5.0 on 2024-02-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_cuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuser',
        ),
    ]
