# Generated by Django 5.0 on 2024-02-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_cuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='id',
        ),
        migrations.AddField(
            model_name='cuser',
            name='username',
            field=models.CharField(default='null', max_length=200, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
