# Generated by Django 5.0 on 2023-12-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='detail',
            field=models.CharField(default='null details', max_length=200),
        ),
        migrations.AddField(
            model_name='features',
            name='name',
            field=models.CharField(default='null name', max_length=100),
        ),
    ]
